### ISSUE TITLE
AttributeError: 'EasyDict' object has no attribute 'replay_path_gif'

### ISSUE THREAD

**Issue by ekiefl** [opendilab/LightZero#155]
## Description

I experienced the following error when running the quickstart command for training tic-tac-toe:

```
▶▶ python3 -u zoo/board_games/tictactoe/config/tictactoe_muzero_bot_mode_config.py
Traceback (most recent call last):
  File "zoo/board_games/tictactoe/config/tictactoe_muzero_bot_mode_config.py", line 86, in <module>
    train_muzero([main_config, create_config], seed=0, max_env_step=max_env_step)
  File "/Users/evan/Software/LightZero/lzero/entry/train_muzero.py", line 73, in train_muzero
    collector_env = create_env_manager(cfg.env.manager, [partial(env_fn, cfg=c) for c in collector_env_cfg])
  File "/Users/evan/anaconda3/envs/lightzero/lib/python3.8/site-packages/ding/envs/env_manager/base_env_manager.py", line 528, in create_env_manager
    return ENV_MANAGER_REGISTRY.build(manager_type, env_fn=env_fn, cfg=manager_cfg)
  File "/Users/evan/anaconda3/envs/lightzero/lib/python3.8/site-packages/ding/utils/registry.py", line 96, in build
    raise e
  File "/Users/evan/anaconda3/envs/lightzero/lib/python3.8/site-packages/ding/utils/registry.py", line 82, in build
    return build_fn(*obj_args, **obj_kwargs)
  File "/Users/evan/anaconda3/envs/lightzero/lib/python3.8/site-packages/ding/envs/env_manager/subprocess_env_manager.py", line 79, in __init__
    super().__init__(env_fn, cfg)
  File "/Users/evan/anaconda3/envs/lightzero/lib/python3.8/site-packages/ding/envs/env_manager/base_env_manager.py", line 109, in __init__
    self._env_ref = self._env_fn[0]()
  File "/Users/evan/Software/LightZero/zoo/board_games/tictactoe/envs/tictactoe_env.py", line 84, in __init__
    self._replay_path_gif = cfg.replay_path_gif
AttributeError: 'EasyDict' object has no attribute 'replay_path_gif'
```

Running the cartpole example yields a similar error:

```
AttributeError: 'EasyDict' object has no attribute 'replay_path'
```

## To reproduce

I installed with `pip install -e .` on the main branch, and my python version is 3.8.10.

I'm very excited to start using LightZero. Thanks in advance for your help.

**Comment by puyuan1996** [comment]
Thank you for your feedback. We have confirmed that this is indeed a bug and have addressed it in our latest [commit](https://github.com/opendilab/LightZero/commit/e763282c4ea149259c568058df4f000aafbb1ab1). Your feedback is highly valuable to us! Should you have any suggestions for improvement, please feel free to share them at any time. We wish you all the best!
