### ISSUE TITLE
Default lunar lander settings result in RuntimeError during model evaluation

### ISSUE THREAD

**Issue by ekiefl** [opendilab/LightZero#164]
## Description

When running `lunarlander_cont_sampled_efficientzero_config.py` without modification, and then `lunarlander_eval.py`, I get the following error:

```
/Users/evan/anaconda3/envs/pooltool_ml/lib/python3.8/site-packages/gym/core.py:329: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/Users/evan/anaconda3/envs/pooltool_ml/lib/python3.8/site-packages/gym/wrappers/step_api_compatibility.py:39: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
Traceback (most recent call last):
  File "/Users/evan/Software/pooltool_ml/LightZero/zoo/box2d/lunarlander/entry/lunarlander_eval.py", line 58, in <module>
    returns_mean, returns = eval_muzero(
  File "/Users/evan/Software/pooltool_ml/LightZero/lzero/entry/eval_muzero.py", line 61, in eval_muzero
    policy.learn_mode.load_state_dict(torch.load(model_path, map_location=cfg.policy.device))
  File "/Users/evan/Software/pooltool_ml/LightZero/lzero/policy/muzero.py", line 774, in _load_state_dict_learn
    self._learn_model.load_state_dict(state_dict['model'])
  File "/Users/evan/anaconda3/envs/pooltool_ml/lib/python3.8/site-packages/torch/nn/modules/module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for MuZeroModelMLP:
	Missing key(s) in state_dict: "prediction_network.fc_policy_head.0.weight", "prediction_network.fc_policy_head.0.bias", "prediction_network.fc_policy_head.1.weight", "prediction_network.fc_policy_head.1.bias", "prediction_network.fc_policy_head.1.running_mean", "prediction_network.fc_policy_head.1.running_var", "prediction_network.fc_policy_head.3.weight", "prediction_network.fc_policy_head.3.bias".
	Unexpected key(s) in state_dict: "dynamics_network.lstm.weight_ih_l0", "dynamics_network.lstm.weight_hh_l0", "dynamics_network.lstm.bias_ih_l0", "dynamics_network.lstm.bias_hh_l0", "prediction_network.fc_policy_head.main.0.weight", "prediction_network.fc_policy_head.main.0.bias", "prediction_network.fc_policy_head.main.2.weight", "prediction_network.fc_policy_head.main.2.bias", "prediction_network.fc_policy_head.mu.weight", "prediction_network.fc_policy_head.mu.bias", "prediction_network.fc_policy_head.log_sigma_layer.weight", "prediction_network.fc_policy_head.log_sigma_layer.bias".
	size mismatch for dynamics_network.fc_dynamics_1.0.weight: copying a param with shape torch.Size([256, 258]) from checkpoint, the shape in current model is torch.Size([256, 260]).
```

## Steps to reproduce

Run the continuous sampled alg:

```bash
lz=<YOUR_LIGHTZERO_DIR>
cd $lz
python zoo/box2d/lunarlander/config/lunarlander_cont_sampled_efficientzero_config.py
```

Wait until the iteration 0 checkpoint is created, then CTRL+C.

Change directory into the output:

```bash
cd data_sez_ctree/lunarlander_cont_sampled_efficientzero_k20_ns50_upc200_rr0.0_seed0
```

Change `$lz/zoo/box2d/lunarlander/entry/lunarlander_eval.py` with the following edits:

```python
    model_path = './ckpt/iteration_0.pth.tar'
    #model_path = None
```

Then run the evaluation:

```bash
python $lz/zoo/box2d/lunarlander/entry/lunarlander_eval.py
```

You should receive the above error.

**Comment by puyuan1996** [comment]
Hello, it appears that the error may have arisen because you did not replace the configuration in the `lunarlander_eval.py` file with the one corresponding to the generated `.ckpt` file. Specifically, you should refer to the code at line two in the following link: [lunarlander_eval.py#L2](https://github.com/opendilab/LightZero/blob/main/zoo/box2d/lunarlander/entry/lunarlander_eval.py#L2). To ensure the program functions correctly, please make sure to use the configuration file that matches the`.ckpt` model file. Best wishes!

**Comment by ekiefl** [comment]
My apologies! Making the necessary import changes fixed things of course.

By the way, I wanted to thank you for your quick and helpful responses.
