### ISSUE TITLE
Bipedal continuous discretized sampled efficientzero config error

### ISSUE THREAD

**Issue by ekiefl** [opendilab/LightZero#165]
I get the following error when running `python zoo/box2d/bipedalwalker/config/bipedalwalker_cont_disc_sampled_efficientzero_config.py` from the root directory:

```
Traceback (most recent call last):
  File "zoo/box2d/bipedalwalker/config/bipedalwalker_cont_disc_sampled_efficientzero_config.py", line 104, in <module>
    train_muzero([main_config, create_config], seed=0, max_env_step=max_env_step)
  File "/home/ubuntu/pooltool-ml/pooltool_ml/LightZero/lzero/entry/train_muzero.py", line 160, in train_muzero
    new_data = collector.collect(train_iter=learner.train_iter, policy_kwargs=collect_kwargs)
  File "/home/ubuntu/pooltool-ml/pooltool_ml/LightZero/lzero/worker/muzero_collector.py", line 411, in collect
    policy_output = self._policy.forward(stack_obs, action_mask, temperature, to_play, epsilon)
  File "/home/ubuntu/pooltool-ml/pooltool_ml/LightZero/lzero/policy/sampled_efficientzero.py", line 841, in _forward_collect
    legal_actions = [
  File "/home/ubuntu/pooltool-ml/pooltool_ml/LightZero/lzero/policy/sampled_efficientzero.py", line 842, in <listcomp>
    [i for i, x in enumerate(action_mask[j]) if x == 1] for j in range(active_collect_env_num)
TypeError: 'NoneType' object is not iterable
```

I encountered this error on two different machines.

**Comment by puyuan1996** [comment]
Hello,
Thank you for your feedback. We have identified this bug and it has now been fixed in the latest [PR](https://github.com/opendilab/LightZero/pull/168). Please test with the updated code. Thanks for your valuable contribution! If you have any suggestions for improvement, please feel free to provide them. Best wishes!

**Comment by ekiefl** [comment]
Thank you for the very fast reply. The error is no longer. I did notice one potential concern I had with the PR though that is relevant to this code: https://github.com/opendilab/LightZero/pull/168#discussion_r1423658475
