### ISSUE TITLE
Tensors on different devices when using GPU (SampledEfficientZeroPolicy)

### ISSUE THREAD

**Issue by ekiefl** [opendilab/LightZero#166]
## Description

I've noticed that when using a GPU, I receive the following error when using the sampled efficient zero algorithm:

```
Traceback (most recent call last):
  File "zoo/box2d/lunarlander/config/lunarlander_cont_sampled_efficientzero_config.py", line 102, in <module>
    train_muzero([main_config, create_config], seed=0, max_env_step=max_env_step)
  File "/home/ubuntu/pooltool-ml/pooltool_ml/LightZero/lzero/entry/train_muzero.py", line 185, in train_muzero
    log_vars = learner.train(train_data, collector.envstep)
  File "/home/ubuntu/pooltool-ml/miniconda/envs/pooltool_ml/lib/python3.8/site-packages/ding/worker/learner/base_learner.py", line 165, in wrapper
    ret = fn(*args, **kwargs)
  File "/home/ubuntu/pooltool-ml/miniconda/envs/pooltool_ml/lib/python3.8/site-packages/ding/worker/learner/base_learner.py", line 205, in train
    log_vars = self._policy.forward(data, **policy_kwargs)
  File "/home/ubuntu/pooltool-ml/pooltool_ml/LightZero/lzero/policy/sampled_efficientzero.py", line 395, in _forward_learn
    policy_loss, policy_entropy, policy_entropy_loss, target_policy_entropy, target_sampled_actions, mu, sigma = self._calculate_policy_loss_cont(
  File "/home/ubuntu/pooltool-ml/pooltool_ml/LightZero/lzero/policy/sampled_efficientzero.py", line 651, in _calculate_policy_loss_cont
    target_sampled_actions_clamped = torch.clamp(
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument min in method wrapper_CUDA_clamp_Tensor)
```

The error does not occur when using a GPU-less environment.

I have experienced this for 3 different environments: bipedal walker, lunar lander, and my own custom environment.

## Steps to reproduce

Make sure you have access to a GPU:

```bash
python -c 'import torch ; print("\nIs available: ", torch.cuda.is_available()) ; print("Pytorch CUDA Compiled version: ", torch._C._cuda_getCompiledVersion()) ; print("Pytorch version: ", torch.__version__) ; print("pytorch file: ", torch.__file__) ; num_of_gpus = torch.cuda.device_count(); print("Number of GPUs: ",num_of_gpus)'
```

For me, I get

```bash
Is available:  True
Pytorch CUDA Compiled version:  12010
Pytorch version:  2.1.1+cu121
pytorch file:  /home/ubuntu/pooltool-ml/miniconda/envs/pooltool_ml/lib/python3.8/site-packages/torch/__init__.py
Number of GPUs:  1
```

Then try either of these runs from the LightZero root:

```python
python zoo/box2d/bipedalwalker/config/bipedalwalker_cont_sampled_efficientzero_config.py
python zoo/box2d/lunarlander/config/lunarlander_cont_sampled_efficientzero_config.py
```

## Environment

```
$ uname -a
Linux 146-235-206-171 6.2.0-37-generic #38~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov  2 18:01:13 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

$ python --version
Python 3.8.10

$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Aug_15_22:02:13_PDT_2023
Cuda compilation tools, release 12.2, V12.2.140
Build cuda_12.2.r12.2/compiler.33191640_0

$ nvidia-smi
Tue Dec 12 06:12:19 2023
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.129.03             Driver Version: 535.129.03   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A10                     On  | 00000000:07:00.0 Off |                    0 |
|  0%   30C    P8              15W / 150W |      4MiB / 23028MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+

$ pip freeze
absl-py==2.0.0
ale-py==0.8.1
appdirs==1.4.4
asttokens==2.4.1
async-timeout==4.0.3
attrs==23.1.0
AutoROM==0.4.2
AutoROM.accept-rom-license==0.6.1
backcall==0.2.0
backports.zoneinfo==0.2.1
bitmath==1.3.3.1
black==23.11.0
boto3==1.33.12
botocore==1.33.12
box2d-py==2.3.5
bsuite==0.3.5
cachetools==5.3.2
cattrs==23.2.3
certifi==2023.11.17
cffi==1.16.0
cfgv==3.4.0
chardet==4.0.0
charset-normalizer==3.3.2
click==7.1.2
cloudpickle==3.0.0
cmake==3.27.9
colored==1.4.4
comm==0.2.0
contourpy==1.1.1
cryptography==41.0.7
cycler==0.12.1
Cython==3.0.6
debugpy==1.8.0
decorator==5.1.1
deprecation==2.1.0
DI-engine==0.5.0
DI-toolkit==0.2.0
DI-treetensor==0.4.1
dill==0.3.7
distlib==0.3.7
dm-env==1.6
dm-tree==0.1.8
docker-pycreds==0.4.0
docutils==0.20.1
easydict==1.9
enum-tools==0.11.0
exceptiongroup==1.2.0
executing==2.0.1
Farama-Notifications==0.0.4
fasteners==0.19
filelock==3.13.1
Flask==1.1.4
fonttools==4.46.0
frozendict==2.3.10
fsspec==2023.12.2
gitdb==4.0.11
GitPython==3.1.40
glfw==2.6.3
google-auth==2.25.2
google-auth-oauthlib==1.0.0
graphviz==0.20.1
grpcio==1.60.0
gym==0.25.1
gym-notices==0.0.8
gymnasium==0.29.1
h5py==3.10.0
hbutils==0.9.3
hickle==5.0.2
huggingface-hub==0.19.4
identify==2.5.33
idna==3.6
imageio==2.33.1
importlib-metadata==7.0.0
importlib-resources==6.1.1
iniconfig==2.0.0
ipykernel==6.27.1
ipython==8.12.3
isort==5.13.1
itsdangerous==1.1.0
jaraco.classes==3.3.0
jedi==0.19.1
jeepney==0.8.0
Jinja2==2.11.3
jmespath==1.0.1
joblib==1.3.2
jupyter_client==8.6.0
jupyter_core==5.5.0
keyring==24.3.0
kiwisolver==1.4.5
lazy_loader==0.3
LightZero==0.0.2
llvmlite==0.41.1
lz4==4.3.2
Markdown==3.5.1
markdown-it-py==3.0.0
MarkupSafe==2.0.1
matplotlib==3.7.4
matplotlib-inline==0.1.6
mdurl==0.1.2
minigrid==2.3.1
mizani==0.9.3
more-itertools==10.1.0
mpire==2.8.1
mpmath==1.3.0
msgpack==1.0.7
msgpack-numpy==0.4.8
mujoco==2.2.0
mujoco-py==2.1.2.14
mypy-extensions==1.0.0
nest-asyncio==1.5.8
networkx==3.1
nh3==0.2.15
nodeenv==1.8.0
numba==0.58.1
numpy==1.24.4
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==8.9.2.26
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-nccl-cu12==2.18.1
nvidia-nvjitlink-cu12==12.3.101
nvidia-nvtx-cu12==12.1.105
oauthlib==3.2.2
opencv-python==4.8.1.78
packaging==23.2
Panda3D==1.10.13
panda3d-gltf==1.0.1
panda3d-simplepbr==0.11.2
pandas==2.0.3
parso==0.8.3
pathspec==0.12.1
patsy==0.5.4
pexpect==4.9.0
pickleshare==0.7.5
Pillow==10.1.0
pkginfo==1.9.6
platformdirs==4.1.0
plotnine==0.12.4
pluggy==1.3.0
pprofile==2.1.0
pre-commit==3.5.0
prompt-toolkit==3.0.41
protobuf==4.25.1
psutil==5.9.6
ptyprocess==0.7.0
pure-eval==0.2.2
py==1.11.0
pyasn1==0.5.1
pyasn1-modules==0.3.0
pycparser==2.21
pygame==2.5.2
Pygments==2.17.2
Pympler==1.0.1
pynng==0.7.2
PyOpenGL==3.1.7
pyparsing==3.1.1
pytest==7.0.1
python-dateutil==2.8.2
pytimeparse==1.1.8
pytz==2023.3.post1
PyWavelets==1.4.1
PyYAML==6.0.1
pyzmq==25.1.2
readme-renderer==42.0
redis==5.0.1
regex==2023.10.3
requests==2.31.0
requests-oauthlib==1.3.1
requests-toolbelt==1.0.0
responses==0.12.1
rfc3986==2.0.0
rich==13.7.0
rsa==4.9
s3transfer==0.8.2
safetensors==0.4.1
scikit-image==0.21.0
scikit-learn==1.3.2
scipy==1.10.1
seaborn==0.13.0
SecretStorage==3.3.3
sentry-sdk==1.38.0
setproctitle==1.3.3
Shimmy==0.2.1
six==1.16.0
smmap==5.0.1
sniffio==1.3.0
stack-data==0.6.3
statsmodels==0.14.0
sympy==1.12
tabulate==0.9.0
tensorboard==2.14.0
tensorboard-data-server==0.7.2
tensorboardX==2.6.2.2
termcolor==2.4.0
threadpoolctl==3.2.0
tifffile==2023.7.10
tokenizers==0.15.0
tomli==2.0.1
torch==2.1.1
tornado==6.4
tqdm==4.66.1
traitlets==5.14.0
transformers==4.36.0
treevalue==1.4.12
triton==2.1.0
trueskill==0.4.5
twine==4.0.2
types-Pillow==10.1.0.2
types-PyYAML==6.0.12.12
typing_extensions==4.9.0
tzdata==2023.3
urllib3==1.26.18
URLObject==2.4.3
virtualenv==20.25.0
wandb==0.16.1
wcwidth==0.2.12
Werkzeug==1.0.1
yapf==0.29.0
yattag==1.15.2
zipp==3.17.0

$ conda list
# packages in environment at /home/ubuntu/pooltool-ml/miniconda/envs/pooltool_ml:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
_openmp_mutex             5.1                       1_gnu
absl-py                   2.0.0                    pypi_0    pypi
ale-py                    0.8.1                    pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
asttokens                 2.4.1                    pypi_0    pypi
async-timeout             4.0.3                    pypi_0    pypi
attrs                     23.1.0                   pypi_0    pypi
autorom                   0.4.2                    pypi_0    pypi
autorom-accept-rom-license 0.6.1                    pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
backports-zoneinfo        0.2.1                    pypi_0    pypi
bitmath                   1.3.3.1                  pypi_0    pypi
black                     23.11.0                  pypi_0    pypi
boto3                     1.33.12                  pypi_0    pypi
botocore                  1.33.12                  pypi_0    pypi
box2d-py                  2.3.5                    pypi_0    pypi
bsuite                    0.3.5                    pypi_0    pypi
ca-certificates           2023.08.22           h06a4308_0
cachetools                5.3.2                    pypi_0    pypi
cattrs                    23.2.3                   pypi_0    pypi
certifi                   2023.11.17               pypi_0    pypi
cffi                      1.16.0                   pypi_0    pypi
cfgv                      3.4.0                    pypi_0    pypi
chardet                   4.0.0                    pypi_0    pypi
charset-normalizer        3.3.2                    pypi_0    pypi
click                     7.1.2                    pypi_0    pypi
cloudpickle               3.0.0                    pypi_0    pypi
cmake                     3.27.9                   pypi_0    pypi
colored                   1.4.4                    pypi_0    pypi
comm                      0.2.0                    pypi_0    pypi
contourpy                 1.1.1                    pypi_0    pypi
cryptography              41.0.7                   pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
cython                    3.0.6                    pypi_0    pypi
debugpy                   1.8.0                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
deprecation               2.1.0                    pypi_0    pypi
di-engine                 0.5.0                    pypi_0    pypi
di-toolkit                0.2.0                    pypi_0    pypi
di-treetensor             0.4.1                    pypi_0    pypi
dill                      0.3.7                    pypi_0    pypi
distlib                   0.3.7                    pypi_0    pypi
dm-env                    1.6                      pypi_0    pypi
dm-tree                   0.1.8                    pypi_0    pypi
docker-pycreds            0.4.0                    pypi_0    pypi
docutils                  0.20.1                   pypi_0    pypi
easydict                  1.9                      pypi_0    pypi
enum-tools                0.11.0                   pypi_0    pypi
exceptiongroup            1.2.0                    pypi_0    pypi
executing                 2.0.1                    pypi_0    pypi
farama-notifications      0.0.4                    pypi_0    pypi
fasteners                 0.19                     pypi_0    pypi
filelock                  3.13.1                   pypi_0    pypi
flask                     1.1.4                    pypi_0    pypi
fonttools                 4.46.0                   pypi_0    pypi
frozendict                2.3.10                   pypi_0    pypi
fsspec                    2023.12.2                pypi_0    pypi
gitdb                     4.0.11                   pypi_0    pypi
gitpython                 3.1.40                   pypi_0    pypi
glfw                      2.6.3                    pypi_0    pypi
google-auth               2.25.2                   pypi_0    pypi
google-auth-oauthlib      1.0.0                    pypi_0    pypi
grpcio                    1.60.0                   pypi_0    pypi
gym                       0.25.1                   pypi_0    pypi
gym-notices               0.0.8                    pypi_0    pypi
gymnasium                 0.29.1                   pypi_0    pypi
h5py                      3.10.0                   pypi_0    pypi
hbutils                   0.9.3                    pypi_0    pypi
hickle                    5.0.2                    pypi_0    pypi
huggingface-hub           0.19.4                   pypi_0    pypi
identify                  2.5.33                   pypi_0    pypi
idna                      3.6                      pypi_0    pypi
imageio                   2.33.1                   pypi_0    pypi
importlib-metadata        7.0.0                    pypi_0    pypi
importlib-resources       6.1.1                    pypi_0    pypi
iniconfig                 2.0.0                    pypi_0    pypi
ipykernel                 6.27.1                   pypi_0    pypi
ipython                   8.12.3                   pypi_0    pypi
isort                     5.13.1                   pypi_0    pypi
itsdangerous              1.1.0                    pypi_0    pypi
jaraco-classes            3.3.0                    pypi_0    pypi
jedi                      0.19.1                   pypi_0    pypi
jeepney                   0.8.0                    pypi_0    pypi
jinja2                    2.11.3                   pypi_0    pypi
jmespath                  1.0.1                    pypi_0    pypi
joblib                    1.3.2                    pypi_0    pypi
jupyter-client            8.6.0                    pypi_0    pypi
jupyter-core              5.5.0                    pypi_0    pypi
keyring                   24.3.0                   pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
lazy-loader               0.3                      pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1
libffi                    3.3                  he6710b0_2
libgcc-ng                 11.2.0               h1234567_1
libgomp                   11.2.0               h1234567_1
libstdcxx-ng              11.2.0               h1234567_1
lightzero                 0.0.3                    pypi_0    pypi
llvmlite                  0.41.1                   pypi_0    pypi
lz4                       4.3.2                    pypi_0    pypi
markdown                  3.5.1                    pypi_0    pypi
markdown-it-py            3.0.0                    pypi_0    pypi
markupsafe                2.0.1                    pypi_0    pypi
matplotlib                3.7.4                    pypi_0    pypi
matplotlib-inline         0.1.6                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
minigrid                  2.3.1                    pypi_0    pypi
mizani                    0.9.3                    pypi_0    pypi
more-itertools            10.1.0                   pypi_0    pypi
mpire                     2.8.1                    pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
msgpack                   1.0.7                    pypi_0    pypi
msgpack-numpy             0.4.8                    pypi_0    pypi
mujoco                    2.2.0                    pypi_0    pypi
mujoco-py                 2.1.2.14                 pypi_0    pypi
mypy-extensions           1.0.0                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0
nest-asyncio              1.5.8                    pypi_0    pypi
networkx                  3.1                      pypi_0    pypi
nh3                       0.2.15                   pypi_0    pypi
nodeenv                   1.8.0                    pypi_0    pypi
numba                     0.58.1                   pypi_0    pypi
numpy                     1.24.4                   pypi_0    pypi
nvidia-cublas-cu12        12.1.3.1                 pypi_0    pypi
nvidia-cuda-cupti-cu12    12.1.105                 pypi_0    pypi
nvidia-cuda-nvrtc-cu12    12.1.105                 pypi_0    pypi
nvidia-cuda-runtime-cu12  12.1.105                 pypi_0    pypi
nvidia-cudnn-cu12         8.9.2.26                 pypi_0    pypi
nvidia-cufft-cu12         11.0.2.54                pypi_0    pypi
nvidia-curand-cu12        10.3.2.106               pypi_0    pypi
nvidia-cusolver-cu12      11.4.5.107               pypi_0    pypi
nvidia-cusparse-cu12      12.1.0.106               pypi_0    pypi
nvidia-nccl-cu12          2.18.1                   pypi_0    pypi
nvidia-nvjitlink-cu12     12.3.101                 pypi_0    pypi
nvidia-nvtx-cu12          12.1.105                 pypi_0    pypi
oauthlib                  3.2.2                    pypi_0    pypi
opencv-python             4.8.1.78                 pypi_0    pypi
openssl                   1.1.1w               h7f8727e_0
packaging                 23.2                     pypi_0    pypi
panda3d                   1.10.13                  pypi_0    pypi
panda3d-gltf              1.0.1                    pypi_0    pypi
panda3d-simplepbr         0.11.2                   pypi_0    pypi
pandas                    2.0.3                    pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
pathspec                  0.12.1                   pypi_0    pypi
patsy                     0.5.4                    pypi_0    pypi
pexpect                   4.9.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    10.1.0                   pypi_0    pypi
pip                       23.3.1           py38h06a4308_0
pkginfo                   1.9.6                    pypi_0    pypi
platformdirs              4.1.0                    pypi_0    pypi
plotnine                  0.12.4                   pypi_0    pypi
pluggy                    1.3.0                    pypi_0    pypi
pprofile                  2.1.0                    pypi_0    pypi
pre-commit                3.5.0                    pypi_0    pypi
prompt-toolkit            3.0.41                   pypi_0    pypi
protobuf                  4.25.1                   pypi_0    pypi
psutil                    5.9.6                    pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
py                        1.11.0                   pypi_0    pypi
pyasn1                    0.5.1                    pypi_0    pypi
pyasn1-modules            0.3.0                    pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pygame                    2.5.2                    pypi_0    pypi
pygments                  2.17.2                   pypi_0    pypi
pympler                   1.0.1                    pypi_0    pypi
pynng                     0.7.2                    pypi_0    pypi
pyopengl                  3.1.7                    pypi_0    pypi
pyparsing                 3.1.1                    pypi_0    pypi
pytest                    7.0.1                    pypi_0    pypi
python                    3.8.10               h12debd9_8
python-dateutil           2.8.2                    pypi_0    pypi
python-graphviz           0.20.1                   pypi_0    pypi
pytimeparse               1.1.8                    pypi_0    pypi
pytz                      2023.3.post1             pypi_0    pypi
pywavelets                1.4.1                    pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
pyzmq                     25.1.2                   pypi_0    pypi
readline                  8.2                  h5eee18b_0
readme-renderer           42.0                     pypi_0    pypi
redis                     5.0.1                    pypi_0    pypi
regex                     2023.10.3                pypi_0    pypi
requests                  2.31.0                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
requests-toolbelt         1.0.0                    pypi_0    pypi
responses                 0.12.1                   pypi_0    pypi
rfc3986                   2.0.0                    pypi_0    pypi
rich                      13.7.0                   pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
s3transfer                0.8.2                    pypi_0    pypi
safetensors               0.4.1                    pypi_0    pypi
scikit-image              0.21.0                   pypi_0    pypi
scikit-learn              1.3.2                    pypi_0    pypi
scipy                     1.10.1                   pypi_0    pypi
seaborn                   0.13.0                   pypi_0    pypi
secretstorage             3.3.3                    pypi_0    pypi
sentry-sdk                1.38.0                   pypi_0    pypi
setproctitle              1.3.3                    pypi_0    pypi
setuptools                66.1.1                   pypi_0    pypi
shimmy                    0.2.1                    pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
smmap                     5.0.1                    pypi_0    pypi
sniffio                   1.3.0                    pypi_0    pypi
sqlite                    3.41.2               h5eee18b_0
stack-data                0.6.3                    pypi_0    pypi
statsmodels               0.14.0                   pypi_0    pypi
sympy                     1.12                     pypi_0    pypi
tabulate                  0.9.0                    pypi_0    pypi
tensorboard               2.14.0                   pypi_0    pypi
tensorboard-data-server   0.7.2                    pypi_0    pypi
tensorboardx              2.6.2.2                  pypi_0    pypi
termcolor                 2.4.0                    pypi_0    pypi
threadpoolctl             3.2.0                    pypi_0    pypi
tifffile                  2023.7.10                pypi_0    pypi
tk                        8.6.12               h1ccaba5_0
tokenizers                0.15.0                   pypi_0    pypi
tomli                     2.0.1                    pypi_0    pypi
torch                     2.1.1                    pypi_0    pypi
tornado                   6.4                      pypi_0    pypi
tqdm                      4.66.1                   pypi_0    pypi
traitlets                 5.14.0                   pypi_0    pypi
transformers              4.36.0                   pypi_0    pypi
treevalue                 1.4.12                   pypi_0    pypi
triton                    2.1.0                    pypi_0    pypi
trueskill                 0.4.5                    pypi_0    pypi
twine                     4.0.2                    pypi_0    pypi
types-pillow              10.1.0.2                 pypi_0    pypi
types-pyyaml              6.0.12.12                pypi_0    pypi
typing-extensions         4.9.0                    pypi_0    pypi
tzdata                    2023.3                   pypi_0    pypi
urllib3                   1.26.18                  pypi_0    pypi
urlobject                 2.4.3                    pypi_0    pypi
virtualenv                20.25.0                  pypi_0    pypi
wandb                     0.16.1                   pypi_0    pypi
wcwidth                   0.2.12                   pypi_0    pypi
werkzeug                  1.0.1                    pypi_0    pypi
wheel                     0.41.2           py38h06a4308_0
xz                        5.4.5                h5eee18b_0
yapf                      0.29.0                   pypi_0    pypi
yattag                    1.15.2                   pypi_0    pypi
zipp                      3.17.0                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_0
```

**Comment by puyuan1996** [comment]
Hello, thank you for your feedback. We have identified this bug and it has now been fixed in the latest [PR](https://github.com/opendilab/LightZero/pull/168). Please test with the updated code. Thanks for your valuable contribution!

**Comment by ekiefl** [comment]
Yes, this fixed things for all 3 environments. Thank you.
