### ISSUE TITLE
How to config to  use multi GPUs to train a model ?

### ISSUE THREAD

**Issue by valkryhx** [opendilab/LightZero#196]
I have 2 GPUs  on a node, so how to set the config to use the 2 GPUs for training?
For now I find that only 1 card is in use.
Thanks.

**Comment by valkryhx** [comment]
I follow the link above ,here is the error info:
2 gpus per node and the rank is 0 and 1 
get_rank()=0
get_rank()=1 with the code here[get_rank()](https://github.com/opendilab/LightZero/blob/3a7424dc260dea8937cce7b96411230832d39c8f/lzero/entry/train_muzero.py#L90)
then tb_logger will be None for the process with rank=1 ,and I got the error,due to the None tb_logger has no attribute 'add_scalar':
_Traceback (most recent call last):
  File "/kaggle/working/LightZero/./zoo/classic_control/grid/config/mygrid_efficientzero_ddp_config.py", line 169, in <module>
    train_muzero([main_config, create_config], seed=0, max_env_step=max_env_step)
  File "/kaggle/working/LightZero/lzero/entry/train_muzero.py", line 138, in train_muzero
    log_buffer_memory_usage(learner.train_iter, replay_buffer, tb_logger)
  File "/kaggle/working/LightZero/lzero/entry/utils.py", line 53, in log_buffer_memory_usage
    writer.add_scalar('Buffer/num_of_all_collected_episodes', buffer.num_of_collected_episodes, train_iter)
AttributeError: 'NoneType' object has no attribute 'add_scalar'
Exception ignored in: <function MuZeroCollector.__del__ at 0x7bb90184fb50>_
But When I comment like this 
 _tb_logger = SummaryWriter(os.path.join('./{}/log/'.format(cfg.exp_name), 'serial')) #if get_rank() == 0 else None_
in the entry/train_muzero.py, another error arises ,also seems to be with the NoneType error.

_Traceback (most recent call last):
  File "/kaggle/working/LightZero/./zoo/classic_control/grid/config/mygrid_efficientzero_ddp_config.py", line 169, in <module>
    train_muzero([main_config, create_config], seed=0, max_env_step=max_env_step)
  File "/kaggle/working/LightZero/lzero/entry/train_muzero.py", line 197, in train_muzero
    log_vars = learner.train(train_data, collector.envstep)
  File "/opt/conda/lib/python3.10/site-packages/ding/worker/learner/base_learner.py", line 165, in wrapper
    ret = fn(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/ding/worker/learner/base_learner.py", line 205, in train
    log_vars = self._policy.forward(data, **policy_kwargs)
  File "/kaggle/working/LightZero/lzero/policy/efficientzero.py", line 476, in _forward_learn
    self.sync_gradients(self._learn_model)
  File "/opt/conda/lib/python3.10/site-packages/ding/policy/base_policy.py", line 427, in sync_gradients
    allreduce(param.grad.data)
AttributeError: 'NoneType' object has no attribute 'data'
Traceback (most recent call last):
  File "/kaggle/working/LightZero/./zoo/classic_control/grid/config/mygrid_efficientzero_ddp_config.py", line 169, in <module>
    train_muzero([main_config, create_config], seed=0, max_env_step=max_env_step)
  File "/kaggle/working/LightZero/lzero/entry/train_muzero.py", line 197, in train_muzero
    log_vars = learner.train(train_data, collector.envstep)
  File "/opt/conda/lib/python3.10/site-packages/ding/worker/learner/base_learner.py", line 165, in wrapper
    ret = fn(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/ding/worker/learner/base_learner.py", line 205, in train
    log_vars = self._policy.forward(data, **policy_kwargs)
  File "/kaggle/working/LightZero/lzero/policy/efficientzero.py", line 476, in _forward_learn
    self.sync_gradients(self._learn_model)
  File "/opt/conda/lib/python3.10/site-packages/ding/policy/base_policy.py", line 427, in sync_gradients
    allreduce(param.grad.data)
AttributeError: 'NoneType' object has no attribute 'data'
Exception ignored in: <function MuZeroCollector.__del__ at 0x7b0d9f22bb50>
Traceback (most recent call last):
  File "/kaggle/working/LightZero/lzero/worker/muzero_collector.py", line 194, in __del__
    self.close()
  File "/kaggle/working/LightZero/lzero/worker/muzero_collector.py", line 183, in close
    self._env.close()
  File "/opt/conda/lib/python3.10/site-packages/ding/envs/env_manager/subprocess_env_manager.py", line 635, in close
    p.send(['close', None, None])
  File "/opt/conda/lib/python3.10/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/opt/conda/lib/python3.10/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/opt/conda/lib/python3.10/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <function MuZeroEvaluator.__del__ at 0x7b0d9f244310>
Traceback (most recent call last):
  File "/kaggle/working/LightZero/lzero/worker/muzero_evaluator.py", line 173, in __del__
    self.close()
  File "/kaggle/working/LightZero/lzero/worker/muzero_evaluator.py", line 162, in close
    self._env.close()
  File "/opt/conda/lib/python3.10/site-packages/ding/envs/env_manager/subprocess_env_manager.py", line 635, in close
    p.send(['close', None, None])
  File "/opt/conda/lib/python3.10/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/opt/conda/lib/python3.10/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/opt/conda/lib/python3.10/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <function MuZeroCollector.__del__ at 0x7c8297717d00>
Traceback (most recent call last):
  File "/kaggle/working/LightZero/lzero/worker/muzero_collector.py", line 194, in __del__
    self.close()
  File "/kaggle/working/LightZero/lzero/worker/muzero_collector.py", line 183, in close
    self._env.close()
  File "/opt/conda/lib/python3.10/site-packages/ding/envs/env_manager/subprocess_env_manager.py", line 635, in close
    p.send(['close', None, None])
  File "/opt/conda/lib/python3.10/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/opt/conda/lib/python3.10/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/opt/conda/lib/python3.10/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <function MuZeroEvaluator.__del__ at 0x7c82977304c0>
Traceback (most recent call last):
  File "/kaggle/working/LightZero/lzero/worker/muzero_evaluator.py", line 173, in __del__
    self.close()
  File "/kaggle/working/LightZero/lzero/worker/muzero_evaluator.py", line 162, in close
    self._env.close()
  File "/opt/conda/lib/python3.10/site-packages/ding/envs/env_manager/subprocess_env_manager.py", line 635, in close
    p.send(['close', None, None])
  File "/opt/conda/lib/python3.10/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/opt/conda/lib/python3.10/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/opt/conda/lib/python3.10/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
[2024-03-15 03:38:50,029] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 11741) of binary: /opt/conda/bin/python3.10
Traceback (most recent call last):
  File "/opt/conda/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
./zoo/classic_control/grid/config/mygrid_efficientzero_ddp_config.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-03-15_03:38:50
  host      : 79ab6f04f1dc
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 11742)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-03-15_03:38:50
  host      : 79ab6f04f1dc
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 11741)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================_

Here is the kaggle link you can refer to .
[kaggle](https://www.kaggle.com/code/shxhuang/notebook53107f13fa)

**Comment by puyuan1996** [comment]
Hello, is your mygrid_efficientzero_ddp_config.py file a modification of the [atari_efficientzero_multigpu_ddp_config.py](https://github.com/opendilab/LightZero/blob/main/zoo/atari/config/atari_efficientzero_multigpu_ddp_config.py) file? Are the relevant settings consistent with it?

**Comment by valkryhx** [comment]
> Hello, is your mygrid_efficientzero_ddp_config.py file a modification of the [atari_efficientzero_multigpu_ddp_config.py](https://github.com/opendilab/LightZero/blob/main/zoo/atari/config/atari_efficientzero_multigpu_ddp_config.py) file? Are the relevant settings consistent with it?

I modified a bit to create the [ddp_config](https://github.com/valkryhx/LightZero/blob/main/zoo/classic_control/grid/config/mygrid_efficientzero_ddp_config.py) according to the atari config file ,  and in the same directory I also created a [mygrid_efficientzero_config.py](https://github.com/valkryhx/LightZero/blob/main/zoo/classic_control/grid/config/mygrid_efficientzero_config.py) whcih can run normally with 1 gpu .

**Comment by puyuan1996** [comment]
- Based on the error information and code you provided, the issue primarily arises during multi-GPU training where only the process with rank 0 creates the TensorBoard's SummaryWriter object, while the tb_logger for other processes is None. This leads to an AttributeError when other processes attempt to use tb_logger. To resolve this issue, you should check if tb_logger is None before using it. If it is None, then skip the logging operations related to it. You can modify the code as follows:
- Add a check for whether writer is None in the function `log_buffer_memory_usage` within [utils.py](https://github.com/opendilab/LightZero/blob/main/lzero/entry/utils.py#L52):
```python
def log_buffer_memory_usage(train_iter, buffer, writer):
    if writer is not None:
        writer.add_scalar('Buffer/num_of_all_collected_episodes', buffer.num_of_collected_episodes, train_iter)
        ...
```
- With the aforementioned modifications, you should be able to resolve the errors caused by tb_logger being None. In this manner, only the process with rank 0 will record TensorBoard logs, while other processes will bypass the logging portion. 

- Hello, please test it according to the above modifications. If there are any problems, we will deal with them later. Due to resource constraints now, we will test and fully fix the above issues in the main branch later.

**Comment by valkryhx** [comment]
Thanks for your reply,I am testing on it.
Besides, during training the model ckpt is saved every 10^4 steps, which is too long.
How to set the save_ckpt_freq in the config file ? I only find the eval_freq.

**Comment by valkryhx** [comment]
After 

> * Based on the error information and code you provided, the issue primarily arises during multi-GPU training where only the process with rank 0 creates the TensorBoard's SummaryWriter object, while the tb_logger for other processes is None. This leads to an AttributeError when other processes attempt to use tb_logger. To resolve this issue, you should check if tb_logger is None before using it. If it is None, then skip the logging operations related to it. You can modify the code as follows:
> * Add a check for whether writer is None in the function `log_buffer_memory_usage` within [utils.py](https://github.com/opendilab/LightZero/blob/main/lzero/entry/utils.py#L52):
> 
> ```python
> def log_buffer_memory_usage(train_iter, buffer, writer):
>     if writer is not None:
>         writer.add_scalar('Buffer/num_of_all_collected_episodes', buffer.num_of_collected_episodes, train_iter)
>         ...
> ```
> 
> * With the aforementioned modifications, you should be able to resolve the errors caused by tb_logger being None. In this manner, only the process with rank 0 will record TensorBoard logs, while other processes will bypass the logging portion.
> * Hello, please test it according to the above modifications. If there are any problems, we will deal with them later. Due to resource constraints now, we will test and fully fix the above issues in the main branch later.

After modification, a new error arises:

Traceback (most recent call last):
  File "/kaggle/working/LightZero/./zoo/classic_control/grid/config/mygrid_efficientzero_ddp_config.py", line 169, in <module>
    train_muzero([main_config, create_config], seed=0, max_env_step=max_env_step)
  File "/kaggle/working/LightZero/lzero/entry/train_muzero.py", line 197, in train_muzero
    log_vars = learner.train(train_data, collector.envstep)
  File "/opt/conda/lib/python3.10/site-packages/ding/worker/learner/base_learner.py", line 165, in wrapper
    ret = fn(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/ding/worker/learner/base_learner.py", line 205, in train
    log_vars = self._policy.forward(data, **policy_kwargs)
  File "/kaggle/working/LightZero/lzero/policy/efficientzero.py", line 476, in _forward_learn
    self.sync_gradients(self._learn_model)
  File "/opt/conda/lib/python3.10/site-packages/ding/policy/base_policy.py", line 427, in sync_gradients
    allreduce(param.grad.data)
AttributeError: 'NoneType' object has no attribute 'data'

**Comment by puyuan1996** [comment]
> save_ckpt_freq

You can control the frequency at which checkpoints (ckpt) are saved by adjusting the `save_ckpt_after_iter` parameter within your [configuration file](https://github.com/valkryhx/LightZero/blob/main/zoo/classic_control/grid/config/mygrid_efficientzero_config.py). To do so, include the `learn` dictionary within your configuration, as demonstrated below:

```python
config = {
    ...
    'eval_freq': int(1e2),
    'learn': {
        'learner': {
            'hook': {
                'log_show_after_iter': 100,
                'save_ckpt_after_iter': 100,   # Set this to your desired frequency
                'save_ckpt_after_run': True,
            },
        },
    },
}
```

By setting the `save_ckpt_after_iter` parameter to the desired number of iterations, you dictate how often a checkpoint should be saved. In the example above, the system is configured to save a checkpoint after every 100 iterations. Adjust this value according to your requirements and resource constraints.

**Comment by puyuan1996** [comment]
> AttributeError: 'NoneType' object has no attribute 'data' 

Hi, we will get back to you later as we are currently facing limitations in accessing GPU resources.

**Comment by puyuan1996** [comment]
> but it does not seem to take effect.

Hello, it should be something like this `mygrid_efficientzero_config.policy.update(save_freq_dict)`

**Comment by puyuan1996** [comment]
Hello,

Thank you for your patience. We have addressed the training issues with `atari_efficientzero_multigpu_ddp_config.py` in this pull request: https://github.com/opendilab/LightZero/pull/200. You are invited to conduct a local test to verify the fixes.

Best wishes.

**Comment by valkryhx** [comment]
Thank you for your detailed reply and help.
I will test the new codes.

**Comment by valkryhx** [comment]
> ```python
> 'save_ckpt_after_iter': 100,
> ```

It works after I modify the policy config as you instruct.
And there comes another question. When I set 'save_ckpt_after_iter': 100,  many temp ckpt will be saved, 
like iteration_100.ckpt  ,iteration_200.ckpt ,etc. 
Then how to remain only a limitied number of  latest ckpts?  Like the latest 5 ckpts?

**Comment by valkryhx** [comment]
> Hello,
> 
> Thank you for your patience. We have addressed the training issues with `atari_efficientzero_multigpu_ddp_config.py` in this pull request: #200. You are invited to conduct a local test to verify the fixes.
> 
> Best wishes.

The fixes really work.

**Comment by valkryhx** [comment]
I test the fixed ddp codes and it really works well. And I find that when I eval the trained model ckpt , a temp dir with model ckpt will be made ,like mygrid_efficientzero_ns40_upc50_rr0_seed0_240320_040558 . Does the evaluation make this ckpt? How to not save it?

**Comment by puyuan1996** [comment]
> Then how to config to just remain only a limitied number of latest ckpts? Like the latest 5 ckpts?

Hello, currently we haven't implemented this feature yet, but it is indeed necessary for saving space. If you're interested, you can submit a pull request to modify the storage logic in this [file](https://github.com/opendilab/DI-engine/blob/aeb4c9c8e1f4ee725cf70894c00e52ef8930f18f/ding/worker/learner/learner_hook.py#L155). For your local environment, I suggest using a script to implement this feature.

**Comment by puyuan1996** [comment]
> How to not save it?

Hello, this file is indeed generated by the evaluation script and it records many key details. Specifically, it is generated at this location: https://github.com/opendilab/DI-engine/blob/main/ding/config/config.py#L465. During the evaluation process, statistical information is written into this file. We recommend retaining the file for subsequent reviews and checks. If you prefer not to keep the file, it currently can only be deleted manually.

**Comment by valkryhx** [comment]
> > How to not save it?
> 
> Hello, this file is indeed generated by the evaluation script and it records many key details. Specifically, it is generated at this location: https://github.com/opendilab/DI-engine/blob/main/ding/config/config.py#L465. During the evaluation process, statistical information is written into this file. We recommend retaining the file for subsequent reviews and checks. If you prefer not to keep the file, it currently can only be deleted manually.

Thank you for your detailed help.
