### ISSUE TITLE
Multi GPU EfficientZero import failure "No module named ding"

### ISSUE THREAD

**Issue by selfsim** [opendilab/LightZero#211]
Attempting to train EfficientZero on Pong with 4 GPUS

Steps to recreate:

`python -m torch.distributed.launch --nproc_per_node=4 LightZero/zoo/atari/config/atari_efficientzero_multigpu_ddp_config.py`

Log:

```(lightenv) [selfsim@cdr2641 selfsim]$ python -m torch.distributed.launch --nproc_per_node=4 LightZero/zoo/atari/config/atari_efficientzero_multigpu_ddp_config.py
/home/selfsim/.local/lib/python3.11/site-packages/torch/distributed/launch.py:183: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions  warnings.warn(
[2024-04-09 15:42:16,625] torch.distributed.run: [WARNING] 
[2024-04-09 15:42:16,625] torch.distributed.run: [WARNING] *****************************************
[2024-04-09 15:42:16,625] torch.distributed.run: [WARNING] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
[2024-04-09 15:42:16,625] torch.distributed.run: [WARNING] *****************************************
Traceback (most recent call last):
  File "/project/6070438/selfsim/LightZero/zoo/atari/config/atari_efficientzero_multigpu_ddp_config.py", line 118, in <module>
    from ding.utils import DDPContext
ModuleNotFoundError: No module named 'ding'
Traceback (most recent call last):
  File "/project/6070438/selfsim/LightZero/zoo/atari/config/atari_efficientzero_multigpu_ddp_config.py", line 118, in <module>
    from ding.utils import DDPContext
ModuleNotFoundError: No module named 'ding'
Traceback (most recent call last):
  File "/project/6070438/selfsim/LightZero/zoo/atari/config/atari_efficientzero_multigpu_ddp_config.py", line 118, in <module>
    from ding.utils import DDPContext
ModuleNotFoundError: No module named 'ding'
Traceback (most recent call last):
  File "/project/6070438/selfsim/LightZero/zoo/atari/config/atari_efficientzero_multigpu_ddp_config.py", line 118, in <module>
    from ding.utils import DDPContext
ModuleNotFoundError: No module named 'ding'
[2024-04-09 15:42:21,643] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 214913) of binary: /cvmfs/soft.computecanada.ca/easybuild/software/2023/x86-64-v3/Compiler/gcccore/python/3.11.5/bin/python
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/selfsim/.local/lib/python3.11/site-packages/torch/distributed/launch.py", line 198, in <module>
    main()
  File "/home/selfsim/.local/lib/python3.11/site-packages/torch/distributed/launch.py", line 194, in main
    launch(args)
  File "/home/selfsim/.local/lib/python3.11/site-packages/torch/distributed/launch.py", line 179, in launch
    run(args)
  File "/home/selfsim/.local/lib/python3.11/site-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/home/selfsim/.local/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/selfsim/.local/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
LightZero/zoo/atari/config/atari_efficientzero_multigpu_ddp_config.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-04-09_15:42:21
  host      : cdr2641.int.cedar.computecanada.ca
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 214914)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-04-09_15:42:21
  host      : cdr2641.int.cedar.computecanada.ca
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 214915)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-04-09_15:42:21
  host      : cdr2641.int.cedar.computecanada.ca
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 214916)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-04-09_15:42:21
  host      : cdr2641.int.cedar.computecanada.ca
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 214913)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================```

**Comment by puyuan1996** [comment]
Hello, the issue you're experiencing may stem from an incorrect installation of the[ DI-engine](https://github.com/opendilab/DI-engine) dependency. Please verify whether you have previously successfully installed LightZero. To install LightZero, follow the steps below, ensuring that no errors occur during the process, as this will also ensure the correct installation of DI-engine:

1. Clone the LightZero repository:
   ```bash
   git clone https://github.com/opendilab/LightZero.git
   ```
2. Navigate to the LightZero directory:
   ```bash
   cd LightZero
   ```
3. Install LightZero and its dependencies:
   ```bash
   pip3 install -e .
   ```

If no errors were encountered in the above steps, DI-engine should be installed correctly. You may try to repeat these steps to resolve the issue, or you can directly install DI-engine using pip:
```bash
pip install DI-engine
```

Ensure that you have a stable network connection during installation to prevent any interruptions that could cause issues. If the problem persists, please provide detailed error information for further assistance in resolving the issue.
