### ISSUE TITLE
Bugs caused by some interface adjustments.

### ISSUE THREAD

**Issue by Jackory** [opendilab/LightZero#32]
After following the README Installation, I run `python3 -u zoo/classic_control/cartpole/config/cartpole_muzero_config.py`. Some bugs occurs:
```
Traceback (most recent call last):
  File "/home/jiangyh/code/LightZero/zoo/classic_control/cartpole/config/cartpole_muzero_config.py", line 93, in <module>
    train_muzero([main_config, create_config], seed=0, max_env_step=max_env_step)
  File "/home/jiangyh/code/LightZero/lzero/entry/train_muzero.py", line 72, in train_muzero
    policy = create_policy(cfg.policy, model=model, enable_field=['learn', 'collect', 'eval'])
  File "/home/jiangyh/miniconda3/envs/lightzero/lib/python3.9/site-packages/ding/policy/base_policy.py", line 344, in create_policy
    return POLICY_REGISTRY.build(cfg.type, cfg=cfg, **kwargs)
  File "/home/jiangyh/miniconda3/envs/lightzero/lib/python3.9/site-packages/ding/utils/registry.py", line 96, in build
    raise e
  File "/home/jiangyh/miniconda3/envs/lightzero/lib/python3.9/site-packages/ding/utils/registry.py", line 82, in build
    return build_fn(*obj_args, **obj_kwargs)
  File "/home/jiangyh/miniconda3/envs/lightzero/lib/python3.9/site-packages/ding/policy/base_policy.py", line 90, in __init__
    model = self._create_model(cfg, model)
  File "/home/jiangyh/miniconda3/envs/lightzero/lib/python3.9/site-packages/ding/policy/base_policy.py", line 144, in _create_model
    return create_model(model_cfg)
  File "/home/jiangyh/miniconda3/envs/lightzero/lib/python3.9/site-packages/ding/model/common/utils.py", line 18, in create_model
    return MODEL_REGISTRY.build(cfg.pop("type"), **cfg)
  File "/home/jiangyh/miniconda3/envs/lightzero/lib/python3.9/site-packages/ding/utils/registry.py", line 96, in build
    raise e
  File "/home/jiangyh/miniconda3/envs/lightzero/lib/python3.9/site-packages/ding/utils/registry.py", line 82, in build
    return build_fn(*obj_args, **obj_kwargs)
  File "/home/jiangyh/code/LightZero/lzero/model/muzero_model_mlp.py", line 104, in __init__
    self.representation_network = RepresentationNetworkMLP(
  File "/home/jiangyh/code/LightZero/lzero/model/common.py", line 260, in __init__
    self.fc_representation = MLP(
TypeError: MLP() got an unexpected keyword argument 'output_norm'
```
I think this may be caused by code interface adjustment.

**Comment by jarlva** [comment]
Have the same issue on a new install

**Comment by puyuan1996** [comment]
Hello, 

Thank you very much for your question.
This error is due to LightZero currently relying on the latest version of DI-engine. You can install it with the following commands:

```
git clone https://github.com/opendilab/DI-engine.git
pip install -e .
```

We will fix this dependency issue as soon as possible. Thank you very much for your attention!

Best wishes.
