### ISSUE TITLE
Clang Issue - `pip install -e .`

### ISSUE THREAD

**Issue by koulanurag** [opendilab/LightZero#52]
HI, I have been following installation issue on M1 -Chip Mac OS.

Any suggestions are appreciated!

```
Building wheels for collected packages: LightZero
  Building editable for LightZero (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building editable for LightZero (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [195 lines of output]
      In file included from /Users/anuragkoul/PycharmProjects/LightZero/lzero/mcts/ctree/ctree_sampled_efficientzero/ezs_tree.cpp:797:
      lzero/mcts/ctree/ctree_sampled_efficientzero/lib/cnode.cpp:86:27: warning: comparison of integers of different signs: 'int' and 'std::vector<float>::size_type' (aka 'unsigned long') [-Wsign-compare]
              for (int i = 0; i < this->value.size(); ++i)
                              ~ ^ ~~~~~~~~~~~~~~~~~~
      lzero/mcts/ctree/ctree_sampled_efficientzero/lib/cnode.cpp:104:31: warning: comparison of integers of different signs: 'int' and 'std::vector<unsigned long>::size_type' (aka 'unsigned long') [-Wsign-compare]
                  for (int i = 1; i < hash.size(); ++i)
                                  ~ ^ ~~~~~~~~~~~
      lzero/mcts/ctree/ctree_sampled_efficientzero/lib/cnode.cpp:374:18: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
                  for (auto prob : probs)
                       ^
      lzero/mcts/ctree/ctree_sampled_efficientzero/lib/cnode.cpp:374:28: warning: range-based for loop is a C++11 extension [-Wc++11-extensions]
                  for (auto prob : probs)
                                 ^
      lzero/mcts/ctree/ctree_sampled_efficientzero/lib/cnode.cpp:384:44: error: no member named '__emplace_back' in 'std::vector<std::pair<int, double> >'; did you mean 'emplace_back'?
                          disc_action_with_probs.__emplace_back(std::make_pair(iter, disturbed_probs[iter]));
                                                 ^~~~~~~~~~~~~~
                                                 emplace_back
      /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/usr/include/c++/v1/vector:591:19: note: 'emplace_back' declared here
              void      emplace_back(_Args&&... __args);
                        ^
      In file included from /Users/anuragkoul/PycharmProjects/LightZero/lzero/mcts/ctree/ctree_sampled_efficientzero/ezs_tree.cpp:797:
      lzero/mcts/ctree/ctree_sampled_efficientzero/lib/cnode.cpp:327:31: warning: comparison of integers of different signs: 'int' and 'std::vector<float>::size_type' (aka 'unsigned long') [-Wsign-compare]
                  for (int i = 0; i < policy_logits.size(); ++i)
                                  ~ ^ ~~~~~~~~~~~~~~~~~~~~
      lzero/mcts/ctree/ctree_sampled_efficientzero/lib/cnode.cpp:331:31: warning: comparison of integers of different signs: 'int' and 'std::vector<float>::size_type' (aka 'unsigned long') [-Wsign-compare]
                  for (int i = 0; i < policy_logits.size(); ++i)
                                  ~ ^ ~~~~~~~~~~~~~~~~~~~~
      lzero/mcts/ctree/ctree_sampled_efficientzero/lib/cnode.cpp:493:14: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
              for (auto a : this->legal_actions)
                   ^
      lzero/mcts/ctree/ctree_sampled_efficientzero/lib/cnode.cpp:493:21: warning: range-based for loop is a C++11 extension [-Wc++11-extensions]
              for (auto a : this->legal_actions)
                          ^
      lzero/mcts/ctree/ctree_sampled_efficientzero/lib/cnode.cpp:573:27: warning: comparison of integers of different signs: 'int' and 'std::vector<tree::CAction>::size_type' (aka 'unsigned long') [-Wsign-compare]
              for (int i = 0; i < traj.size(); ++i)
                              ~ ^ ~~~~~~~~~~~
      lzero/mcts/ctree/ctree_sampled_efficientzero/lib/cnode.cpp:591:18: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
                  for (auto a : this->legal_actions)
                       ^
      lzero/mcts/ctree/ctree_sampled_efficientzero/lib/cnode.cpp:591:25: warning: range-based for loop is a C++11 extension [-Wc++11-extensions]
                  for (auto a : this->legal_actions)
                              ^
      lzero/mcts/ctree/ctree_sampled_efficientzero/lib/cnode.cpp:662:35: warning: comparison of integers of different signs: 'int' and 'std::vector<std::vector<float> >::size_type' (aka 'unsigned long') [-Wsign-compare]
                      for (int i = 0; i < this->legal_actions_list.size(); ++i)
                                      ~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      lzero/mcts/ctree/ctree_sampled_efficientzero/lib/cnode.cpp:776:31: warning: comparison of integers of different signs: 'int' and 'std::vector<tree::CAction>::size_type' (aka 'unsigned long') [-Wsign-compare]
                  for (int j = 0; j < this->roots[i].legal_actions.size(); ++j)
                                  ~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      lzero/mcts/ctree/ctree_sampled_efficientzero/lib/cnode.cpp:843:18: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
                  for (auto a : node->legal_actions)
                       ^
      lzero/mcts/ctree/ctree_sampled_efficientzero/lib/cnode.cpp:843:25: warning: range-based for loop is a C++11 extension [-Wc++11-extensions]
                  for (auto a : node->legal_actions)
                              ^
      lzero/mcts/ctree/ctree_sampled_efficientzero/lib/cnode.cpp:815:15: warning: unused variable 'parent_value_prefix' [-Wunused-variable]
              float parent_value_prefix = 0.0;
                    ^
      lzero/mcts/ctree/ctree_sampled_efficientzero/lib/cnode.cpp:992:14: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
              for (auto a : root->legal_actions)
                   ^
      lzero/mcts/ctree/ctree_sampled_efficientzero/lib/cnode.cpp:992:21: warning: range-based for loop is a C++11 extension [-Wc++11-extensions]
              for (auto a : root->legal_actions)
                          ^
      lzero/mcts/ctree/ctree_sampled_efficientzero/lib/cnode.cpp:1057:35: warning: comparison of integers of different signs: 'int' and 'std::map<unsigned long, tree::CNode>::size_type' (aka 'unsigned long') [-Wsign-compare]
                      for (int i = 0; i < parent->children.size(); ++i)
                                      ~ ^ ~~~~~~~~~~~~~~~~~~~~~~~
      lzero/mcts/ctree/ctree_sampled_efficientzero/lib/cnode.cpp:1066:35: warning: comparison of integers of different signs: 'int' and 'std::map<unsigned long, tree::CNode>::size_type' (aka 'unsigned long') [-Wsign-compare]
                      for (int i = 0; i < parent->children.size(); ++i)
                                      ~ ^ ~~~~~~~~~~~~~~~~~~~~~~~
      In file included from /Users/anuragkoul/PycharmProjects/LightZero/lzero/mcts/ctree/ctree_sampled_efficientzero/ezs_tree.cpp:801:
      In file included from /private/var/folders/53/kbc84lyx1kl8rhp418nhwgl80000gn/T/pip-build-env-grfikt64/overlay/lib/python3.8/site-packages/numpy/core/include/numpy/arrayobject.h:5:
      In file included from /private/var/folders/53/kbc84lyx1kl8rhp418nhwgl80000gn/T/pip-build-env-grfikt64/overlay/lib/python3.8/site-packages/numpy/core/include/numpy/ndarrayobject.h:12:
      In file included from /private/var/folders/53/kbc84lyx1kl8rhp418nhwgl80000gn/T/pip-build-env-grfikt64/overlay/lib/python3.8/site-packages/numpy/core/include/numpy/ndarraytypes.h:1940:
      /private/var/folders/53/kbc84lyx1kl8rhp418nhwgl80000gn/T/pip-build-env-grfikt64/overlay/lib/python3.8/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: "Using deprecated NumPy API, disable it with "          "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
      #warning "Using deprecated NumPy API, disable it with " \
       ^
      /Users/anuragkoul/PycharmProjects/LightZero/lzero/mcts/ctree/ctree_sampled_efficientzero/ezs_tree.cpp:6679:3: warning: 'tp_print' is deprecated [-Wdeprecated-declarations]
        0, /*tp_print*/
        ^
      /opt/homebrew/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/include/python3.8/cpython/object.h:260:5: note: 'tp_print' has been explicitly marked deprecated here
          Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
          ^
      /opt/homebrew/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/include/python3.8/pyport.h:515:54: note: expanded from macro 'Py_DEPRECATED'
      #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
                                                           ^
      /Users/anuragkoul/PycharmProjects/LightZero/lzero/mcts/ctree/ctree_sampled_efficientzero/ezs_tree.cpp:6787:3: warning: 'tp_print' is deprecated [-Wdeprecated-declarations]
        0, /*tp_print*/
        ^
      /opt/homebrew/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/include/python3.8/cpython/object.h:260:5: note: 'tp_print' has been explicitly marked deprecated here
          Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
          ^
      /opt/homebrew/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/include/python3.8/pyport.h:515:54: note: expanded from macro 'Py_DEPRECATED'
      #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
                                                           ^
      /Users/anuragkoul/PycharmProjects/LightZero/lzero/mcts/ctree/ctree_sampled_efficientzero/ezs_tree.cpp:6896:3: warning: 'tp_print' is deprecated [-Wdeprecated-declarations]
        0, /*tp_print*/
        ^
      /opt/homebrew/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/include/python3.8/cpython/object.h:260:5: note: 'tp_print' has been explicitly marked deprecated here
          Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
          ^
      /opt/homebrew/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/include/python3.8/pyport.h:515:54: note: expanded from macro 'Py_DEPRECATED'
      #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
                                                           ^
      /Users/anuragkoul/PycharmProjects/LightZero/lzero/mcts/ctree/ctree_sampled_efficientzero/ezs_tree.cpp:7022:3: warning: 'tp_print' is deprecated [-Wdeprecated-declarations]
        0, /*tp_print*/
        ^
      /opt/homebrew/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/include/python3.8/cpython/object.h:260:5: note: 'tp_print' has been explicitly marked deprecated here
          Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
          ^
      /opt/homebrew/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/include/python3.8/pyport.h:515:54: note: expanded from macro 'Py_DEPRECATED'
      #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
                                                           ^
      /Users/anuragkoul/PycharmProjects/LightZero/lzero/mcts/ctree/ctree_sampled_efficientzero/ezs_tree.cpp:7130:3: warning: 'tp_print' is deprecated [-Wdeprecated-declarations]
        0, /*tp_print*/
        ^
      /opt/homebrew/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/include/python3.8/cpython/object.h:260:5: note: 'tp_print' has been explicitly marked deprecated here
          Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
          ^
      /opt/homebrew/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/include/python3.8/pyport.h:515:54: note: expanded from macro 'Py_DEPRECATED'
      #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
                                                           ^
      26 warnings and 1 error generated.
      Traceback (most recent call last):
        File "/private/var/folders/53/kbc84lyx1kl8rhp418nhwgl80000gn/T/pip-build-env-grfikt64/overlay/lib/python3.8/site-packages/setuptools/_distutils/unixccompiler.py", line 185, in _compile
          self.spawn(compiler_so + cc_args + [src, '-o', obj] + extra_postargs)
        File "/private/var/folders/53/kbc84lyx1kl8rhp418nhwgl80000gn/T/pip-build-env-grfikt64/overlay/lib/python3.8/site-packages/setuptools/_distutils/ccompiler.py", line 1041, in spawn
          spawn(cmd, dry_run=self.dry_run, **kwargs)
        File "/private/var/folders/53/kbc84lyx1kl8rhp418nhwgl80000gn/T/pip-build-env-grfikt64/overlay/lib/python3.8/site-packages/setuptools/_distutils/spawn.py", line 70, in spawn
          raise DistutilsExecError(
      distutils.errors.DistutilsExecError: command '/usr/bin/clang' failed with exit code 1
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/private/var/folders/53/kbc84lyx1kl8rhp418nhwgl80000gn/T/pip-build-env-grfikt64/overlay/lib/python3.8/site-packages/setuptools/command/editable_wheel.py", line 155, in run
          self._create_wheel_file(bdist_wheel)
        File "/private/var/folders/53/kbc84lyx1kl8rhp418nhwgl80000gn/T/pip-build-env-grfikt64/overlay/lib/python3.8/site-packages/setuptools/command/editable_wheel.py", line 344, in _create_wheel_file
          files, mapping = self._run_build_commands(dist_name, unpacked, lib, tmp)
        File "/private/var/folders/53/kbc84lyx1kl8rhp418nhwgl80000gn/T/pip-build-env-grfikt64/overlay/lib/python3.8/site-packages/setuptools/command/editable_wheel.py", line 267, in _run_build_commands
          self._run_build_subcommands()
        File "/private/var/folders/53/kbc84lyx1kl8rhp418nhwgl80000gn/T/pip-build-env-grfikt64/overlay/lib/python3.8/site-packages/setuptools/command/editable_wheel.py", line 294, in _run_build_subcommands
          self.run_command(name)
        File "/private/var/folders/53/kbc84lyx1kl8rhp418nhwgl80000gn/T/pip-build-env-grfikt64/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/53/kbc84lyx1kl8rhp418nhwgl80000gn/T/pip-build-env-grfikt64/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/private/var/folders/53/kbc84lyx1kl8rhp418nhwgl80000gn/T/pip-build-env-grfikt64/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/53/kbc84lyx1kl8rhp418nhwgl80000gn/T/pip-build-env-grfikt64/overlay/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/private/var/folders/53/kbc84lyx1kl8rhp418nhwgl80000gn/T/pip-build-env-grfikt64/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/private/var/folders/53/kbc84lyx1kl8rhp418nhwgl80000gn/T/pip-build-env-grfikt64/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/private/var/folders/53/kbc84lyx1kl8rhp418nhwgl80000gn/T/pip-build-env-grfikt64/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "/private/var/folders/53/kbc84lyx1kl8rhp418nhwgl80000gn/T/pip-build-env-grfikt64/overlay/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
          _build_ext.build_extension(self, ext)
        File "/private/var/folders/53/kbc84lyx1kl8rhp418nhwgl80000gn/T/pip-build-env-grfikt64/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
          objects = self.compiler.compile(
        File "/private/var/folders/53/kbc84lyx1kl8rhp418nhwgl80000gn/T/pip-build-env-grfikt64/overlay/lib/python3.8/site-packages/setuptools/_distutils/ccompiler.py", line 600, in compile
          self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
        File "/private/var/folders/53/kbc84lyx1kl8rhp418nhwgl80000gn/T/pip-build-env-grfikt64/overlay/lib/python3.8/site-packages/setuptools/_distutils/unixccompiler.py", line 187, in _compile
          raise CompileError(msg)
      distutils.errors.CompileError: command '/usr/bin/clang' failed with exit code 1
      /private/var/folders/53/kbc84lyx1kl8rhp418nhwgl80000gn/T/pip-build-env-grfikt64/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py:988: _DebuggingTips: Problem in editable installation.
      !!
      
              ********************************************************************************
              An error happened while installing `LightZero` in editable mode.
      
              The following steps are recommended to help debug this problem:
      
              - Try to install the project normally, without using the editable mode.
                Does the error still persist?
                (If it does, try fixing the problem before attempting the editable mode).
              - If you are using binary extensions, make sure you have all OS-level
                dependencies installed (e.g. compilers, toolchains, binary libraries, ...).
              - Try the latest version of setuptools (maybe the error was already fixed).
              - If you (or your project dependencies) are using any setuptools extension
                or customization, make sure they support the editable mode.
      
              After following the steps above, if the problem still persists and
              you think this is related to how setuptools handles editable installations,
              please submit a reproducible example
              (see https://stackoverflow.com/help/minimal-reproducible-example) to:
      
                  https://github.com/pypa/setuptools/issues
      
              See https://setuptools.pypa.io/en/latest/userguide/development_mode.html for details.
              ********************************************************************************
      
      !!
        cmd_obj.run()
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building editable for LightZero
Failed to build LightZero
ERROR: Could not build wheels for LightZero, which is required to install pyproject.toml-based projects

```

**Comment by puyuan1996** [comment]
Hello,

This error might be related to different C++ versions on different operating system versions.

Specifically, as the traceback suggests, this error occurs because there is no member function named `__emplace_back` in the C++ `std::vector` class. You should use the `emplace_back` function, which was introduced in C++11, for in-place construction of new elements at the end of the container. Please change `__emplace_back` to `emplace_back` in the code as follows:

`disc_action_with_probs.emplace_back(std::make_pair(iter, disturbed_probs[iter]));`

This should fix the compilation error and correctly add the new element to the end of the `disc_action_with_probs` vector.

Best wishes.

**Comment by koulanurag** [comment]
Thanks for suggesting the fix. I will try it out.

Also, I assume, It will be helpful to others if the required C++ version is specified in README.

Thanks again.
