### ISSUE TITLE
Get a error when "pip install -e ."

### ISSUE THREAD

**Issue by Uptomylimit** [opendilab/LightZero#53]
I am trying to install your package with the code "pip install -e ."
But I get a error about "cl.exe". 
Any suggestions are appreciated!

````
Building wheels for collected packages: LightZero
  Building editable for LightZero (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building editable for LightZero (pyproject.toml) did not run successfully.
  `│` exit code: 1
  ╰─> [87 lines of output]
      C:\Users\Lenovo\AppData\Local\Temp\pip-build-env-5kdgr35h\overlay\Lib\site-packages\wheel\bdist_wheel.py:100: RuntimeWarning: Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
        if get_flag("Py_DEBUG", hasattr(sys, "gettotalrefcount"), warn=(impl == "cp")):
      ez_tree.cpp
      C:\work\project\pycharm\swing_snake\LightZero-main\lzero\mcts\ctree\ctree_efficientzero\lib/cnode.cpp(1): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
      C:\work\project\pycharm\swing_snake\LightZero-main\lzero\mcts\ctree\ctree_efficientzero\lib/cnode.cpp(105): warning C4267: “初始化”: 从“size_t”转换到“int”，可能丢失数据
      C:\work\project\pycharm\swing_snake\LightZero-main\lzero\mcts\ctree\ctree_efficientzero\lib/cnode.cpp(135): error C2065: “policy”: 未声明的标识符
      C:\work\project\pycharm\swing_snake\LightZero-main\lzero\mcts\ctree\ctree_efficientzero\lib/cnode.cpp(141): error C2065: “policy”: 未声明的标识符
      C:\work\project\pycharm\swing_snake\LightZero-main\lzero\mcts\ctree\ctree_efficientzero\lib/cnode.cpp(147): error C2065: “policy”: 未声明的标识符
      C:\work\project\pycharm\swing_snake\LightZero-main\lzero\mcts\ctree\ctree_efficientzero\lib/cnode.cpp(147): error C2541: “delete”: 不能删除不是指针的对象
      C:\work\project\pycharm\swing_snake\LightZero-main\lzero\mcts\ctree\ctree_efficientzero\lib/cnode.cpp(503): warning C4267: “初始化”: 从“size_t”转换到“int”，可能丢失数据
      C:\work\project\pycharm\swing_snake\LightZero-main\lzero\mcts\ctree\ctree_efficientzero\lib/cnode.cpp(535): warning C4267: “初始化”: 从“size_t”转换到“int”，可能丢失数据
      C:\work\project\pycharm\swing_snake\LightZero-main\lzero\mcts\ctree\ctree_efficientzero\lib/cnode.cpp(624): warning C4305: “初始化”: 从“double”到“float”截断
      C:\work\project\pycharm\swing_snake\LightZero-main\lzero\mcts\ctree\ctree_efficientzero\lib/cnode.cpp(629): warning C4244: “参数”: 从“int”转换到“float”，可能丢失数据
      C:\work\project\pycharm\swing_snake\LightZero-main\lzero\mcts\ctree\ctree_efficientzero\lib/cnode.cpp(629): warning C4244: “参数”: 从“int”转换到“float”，可能丢失数据
      Traceback (most recent call last):
        File "C:\Users\Lenovo\AppData\Local\Temp\pip-build-env-5kdgr35h\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 419, in compile
          self.spawn(args)
        File "C:\Users\Lenovo\AppData\Local\Temp\pip-build-env-5kdgr35h\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 517, in spawn
          return super().spawn(cmd, env=env)
        File "C:\Users\Lenovo\AppData\Local\Temp\pip-build-env-5kdgr35h\overlay\Lib\site-packages\setuptools\_distutils\ccompiler.py", line 1041, in spawn
          spawn(cmd, dry_run=self.dry_run, **kwargs)
        File "C:\Users\Lenovo\AppData\Local\Temp\pip-build-env-5kdgr35h\overlay\Lib\site-packages\setuptools\_distutils\spawn.py", line 70, in spawn
          raise DistutilsExecError(
      distutils.errors.DistutilsExecError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
     
      During handling of the above exception, another exception occurred:
     
      Traceback (most recent call last):
        File "C:\Users\Lenovo\AppData\Local\Temp\pip-build-env-5kdgr35h\overlay\Lib\site-packages\setuptools\command\editable_wheel.py", line 155, in run
          self._create_wheel_file(bdist_wheel)
        File "C:\Users\Lenovo\AppData\Local\Temp\pip-build-env-5kdgr35h\overlay\Lib\site-packages\setuptools\command\editable_wheel.py", line 344, in _create_wheel_file
          files, mapping = self._run_build_commands(dist_name, unpacked, lib, tmp)
        File "C:\Users\Lenovo\AppData\Local\Temp\pip-build-env-5kdgr35h\overlay\Lib\site-packages\setuptools\command\editable_wheel.py", line 267, in _run_build_commands
          self._run_build_subcommands()
        File "C:\Users\Lenovo\AppData\Local\Temp\pip-build-env-5kdgr35h\overlay\Lib\site-packages\setuptools\command\editable_wheel.py", line 294, in _run_build_subcommands
          self.run_command(name)
        File "C:\Users\Lenovo\AppData\Local\Temp\pip-build-env-5kdgr35h\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Lenovo\AppData\Local\Temp\pip-build-env-5kdgr35h\overlay\Lib\site-packages\setuptools\dist.py", line 1234, in run_command
          super().run_command(command)
        File "C:\Users\Lenovo\AppData\Local\Temp\pip-build-env-5kdgr35h\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\Lenovo\AppData\Local\Temp\pip-build-env-5kdgr35h\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 84, in run
          _build_ext.run(self)
        File "C:\Users\Lenovo\AppData\Local\Temp\pip-build-env-5kdgr35h\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
          self.build_extensions()
        File "C:\Users\Lenovo\AppData\Local\Temp\pip-build-env-5kdgr35h\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "C:\Users\Lenovo\AppData\Local\Temp\pip-build-env-5kdgr35h\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "C:\Users\Lenovo\AppData\Local\Temp\pip-build-env-5kdgr35h\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 246, in build_extension
          _build_ext.build_extension(self, ext)
        File "C:\Users\Lenovo\AppData\Local\Temp\pip-build-env-5kdgr35h\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 548, in build_extension
          objects = self.compiler.compile(
        File "C:\Users\Lenovo\AppData\Local\Temp\pip-build-env-5kdgr35h\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 421, in compile
          raise CompileError(msg)
      distutils.errors.CompileError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      C:\Users\Lenovo\AppData\Local\Temp\pip-build-env-5kdgr35h\overlay\Lib\site-packages\setuptools\_distutils\dist.py:988: _DebuggingTips: Problem in editable installation.
      !!
     
              ********************************************************************************
              An error happened while installing `LightZero` in editable mode.
     
              The following steps are recommended to help debug this problem:
     
              - Try to install the project normally, without using the editable mode.
                Does the error still persist?
                (If it does, try fixing the problem before attempting the editable mode).
              - If you are using binary extensions, make sure you have all OS-level
                dependencies installed (e.g. compilers, toolchains, binary libraries, ...).
              - Try the latest version of setuptools (maybe the error was already fixed).
              - If you (or your project dependencies) are using any setuptools extension
                or customization, make sure they support the editable mode.
     
              After following the steps above, if the problem still persists and
              you think this is related to how setuptools handles editable installations,
              please submit a reproducible example
              (see https://stackoverflow.com/help/minimal-reproducible-example) to:
     
                  https://github.com/pypa/setuptools/issues
     
              See https://setuptools.pypa.io/en/latest/userguide/development_mode.html for details.
              ********************************************************************************
     
      !!
        cmd_obj.run()
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building editable for LightZero
Failed to build LightZero
ERROR: Could not build wheels for LightZero, which is required to install pyproject.toml-based projects

**Comment by PaParaZz1** [comment]
Please note that LightZero only supports Linux and macOS platform now. For Windows platform, there are some bugs on different compiler settings, so we don't add a stable version on Windows.

I suggest that you can use Linux and macOS platform, or utilize docker on Windows to run programs in LightZero. If you have other problems, we can continue to ask within this issue.

**Comment by nrkarp** [comment]
FYI, working from a fresh environment on a newly created ubuntu 20.04 instance I got a host of errors for incompatible or missing packages when following the installation instructions.

Eventually I was able to get everything to install without error as follows:

    1  python -m venv venv
    2  . venv/bin/activate
    3  pip3 install --upgrade "click<8.0,>=7.1" "protobuf!=4.21.0,<5,>=3.12.0" "pygments<3.0.0,>=2.13.0" "typing-extensions<5.0,>=4.0.0" "setuptools>=50.0,<=66.1.1" "zipp>=3.1.0" "testresources" torch appdirs>=1.4.3 psutil>=5.0.0 cloudpickle h5py
    4  pip3 install --upgrade matplotlib pandas scikit-learn scipy PyYAML "urllib3<2.0" tensorboard "Jinja2<3.0,>=2.10.1" "Werkzeug<2.0,>=0.15" "MarkupSafe==2.0.1" numba
    5  git clone https://github.com/opendilab/LightZero.git
    6  cd LightZero/
    7  pip3 install -e .
    8  history

**Comment by puyuan1996** [comment]
Thank you for your valuable suggestion. Indeed, it is crucial to have clear installation and compatibility requirements. We plan to address this matter shortly by updating the relevant details in our README file. Thanks!

**Comment by DominikRoB** [comment]
As suggested above here is a minimum dockerfile to run the cartpole example, if anyone needs it.

```
FROM python:3.9-slim

WORKDIR /app

# Update and install gcc, g++, and swig
RUN apt-get update && \
    apt-get install -y gcc g++ swig && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install git
RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*

# Update pip and setuptools
RUN python -m pip install --upgrade pip setuptools

# Clone and install the package in editable mode
RUN git clone https://github.com/opendilab/LightZero.git
RUN pip install -e ./LightZero


CMD ["python", "./LightZero/zoo/classic_control/cartpole/config/cartpole_muzero_config.py"]
```
